### ISSUE TITLE
type error

### ISSUE THREAD

**Issue by prtkg** [opentsdb-js/client#1]
A) error

D:\nodejslearning\opentsdb>node index.js

D:\nodejslearning\opentsdb\index.js:7
    .aggregator( 'max' )
     ^
TypeError: Object function newQuery(){
                return new Query();
        } has no method 'aggregator'
    at Object.<anonymous> (D:\nodejslearning\opentsdb\index.js:7:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

D:\nodejslearning\opentsdb>

B) code 

var client = require( 'opentsdb-client' ),
    mQuery = require( 'opentsdb-mquery' );

mQuery
    .aggregator( 'max' )
    .metric( 'proc.cpu.uti' )
    .tags( 'dev', '*' );

client
    .host( 'leaving empty' )
    .port( 8080 )
    .ms( true )
    .arrays( true )
    .tsuids( true )
    .annotations( 'all' )
    .start( '2014/02/25-13:00:00' )
    .end( '2014/02/25-14:00:00' )
    .queries( mQuery )
    .get( function onData( error, data ) {
        if ( error ) {
            console.error( JSON.stringify( error ) );
            return;
        }
        console.log( JSON.stringify( data ) );
    });

C) output expected -

[{"metric":"proc.cpu.uti","tags":{"dev":"routerA"},"aggregateTags":[],"tsuids":["00000300000200004B"],"dps":[[1393313404000,3],[1393313704000,3],[1393314008000,4],[1393314304000,3],[1393314604000,3],[1393314904000,3],[1393315204000,3],[1393315504000,3],[1393315804000,3],[1393316104000,3],[1393316407000,3],[1393316704000,3]]}]

**Comment by kgryte** [comment]
I will take a look at this, and let you know what I find later today.

**Comment by kgryte** [comment]
Sorry, the example code in the README is wrong. I will update this. But briefly, the following should work:

``` javascript
var createClient = require( 'opentsdb-client' ),
    createQuery = require( 'opentsdb-mquery' );

var client = createClient(),
    mQuery = createQuery();

mQuery
    .aggregator( 'max' )
    .metric( 'proc.cpu.uti' )
    .tags( 'dev', '*' );

client
    .host( 'leaving empty' )
    .port( 8080 )
    .ms( true )
    .arrays( true )
    .tsuids( true )
    .annotations( 'all' )
    .start( '2014/02/25-13:00:00' )
    .end( '2014/02/25-14:00:00' )
    .queries( mQuery )
    .get( function onData( error, data ) {
        if ( error ) {
            console.error( JSON.stringify( error ) );
            return;
        }
        console.log( JSON.stringify( data ) );
    });
```

**Comment by kgryte** [comment]
Updated module and pushed a new release. Let me know if you find any other issues.

**Comment by prtkg** [comment]
Thanks a lot !!!!!!!!

Really appreciate the prompt response.
It's working. I will get back to you if any doubts.

**Comment by kgryte** [comment]
No problem.
